In [ ]:
# W10D1

In [3]:
# esercizio 1
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [4]:
# per come è scritta, la lista è data da 3 mini liste: potrebbe rappresentare una matrice 3 x 5; un array bidimensionale
# elemento della seconda riga che occupa la quarta posizione
print(mat[1][3])

8


In [5]:
print(mat[2][4])

14


In [6]:
# esercizio 2
# Importiamo il modulo math e proviamo a usare le funzioni .sin() .cos() .factorial() e la variabile .pi la riconoscete?
import math

In [20]:
math.sin((math.pi/6)) # angoli in radianti
print("sin(pi/6 rad) =", math.sin(math.pi/6))

sin(pi/6 rad) = 0.49999999999999994


In [22]:
math.cos((math.pi/3)) # angoli in radianti
print("cos(pi/3 rad) =", math.cos(math.pi/3))

cos(pi/3 rad) = 0.5000000000000001


In [11]:
math.factorial(5)

120

In [12]:
math.pi # p greco

3.141592653589793

In [18]:
# definisco gli angoli in radianti
rad30 = math.radians(30)
rad60 = math.radians(60)

# Calcolo seno e coseno
print("sin(30°) =", math.sin(rad30))  
print("cos(60°) =", math.cos(rad60))  

sin(30°) = 0.49999999999999994
cos(60°) = 0.5000000000000001


In [23]:
# esercio 3
math.degrees(math.pi)

180.0

In [ ]:
# è l'angolo associato a p-greco: cioè, 180 gradi!!

In [24]:
help(math.degrees) #  Convert angle x from radians to degrees.

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [25]:
# esercio 4
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]

In [28]:
import  numpy as np
lst = np.array(lst)

# vendita minima, massima e media
print(lst.min())
print(lst.max())
print(lst.mean())

1280
8150
4634.166666666667


In [34]:
filtro5000 = lst > 5000 # creo un filtro
print(filtro5000) # stampo l'output booleano del filtro
print(lst[filtro5000]) # vedo quali sono 
print(len(lst[filtro5000])) # vedo quante sono le vendite magg di 5000

[False  True  True False False False False False  True  True  True  True]
[5500 7200 6410 8150 7100 5350]
6


In [36]:
filtro3000 = lst < 3000
print(filtro3000) # stampo l'output booleano del filtro
print(lst[filtro3000]) # vedo quali sono 
print(len(lst[filtro3000])) # vedo quante sono le vendite magg di 3000

[ True False False False  True  True  True False False False False False]
[2000 1280 1900 2500]
4


In [38]:
# esercizio 5 
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000} # dizionario

In [39]:
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005)) # listra + indice

In [44]:
fatturati_dict[1997] 
fatturati_series[1997]

12000

In [43]:
fatturati_series[2004]

21000

In [ ]:
# il dizionario è una struttura dati che associa coppie chiave-valore; una collezione mutabile e non ordinata di elementi.
# le series è sempre una collezione di dati con chiave e valore, solo che vengono specificati a parte, 
# dove l'ordinamento è quello della lista scritta e dell’indice che viene fornito, 
# che può essere di qualsiasi tipo purché specificato

# con le serie è possibile fare operazioni matematiche vettoriali su tutti i valori, 
# filtrare e slicing avanzati perché si trasformano direttamente in array etichettatto.

In [45]:
# esercizio 6
import numpy as np 
stipendi = np.array( [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000] )

In [46]:
# dobbiamo raddoppiare gli stipendi
# metodo 1: ciclo for
for stipendio in stipendi:
    print(stipendio * 2)

200
400
600
800
1000
1200
1400
1600
1800
2000


In [47]:
# metodo 2: masking
stipendi * 2

array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])

In [49]:
# esercizio 7
# Scrivere un programma che, data una lista di numeri, fornisca in output i tre numeri più grandi; 
# gestire il caso in cui la lista sia più corta di tre, e quando uno o più dei numeri selezionati sono uguali.
import numpy as np

numeri = np.array([5, 25, 7, 3, 12, 9]) 

if len(numeri) < 3:
    print("La lista ha meno di 3 numeri:", numeri)
else:
    top3 = np.sort(numeri)[-3:]
    print("I tre numeri più grandi sono:", top3)


I tre numeri più grandi sono: [ 9 12 25]


In [50]:
import numpy as np

numeri = np.array([5, 25,]) 

if len(numeri) < 3:
    print("La lista ha meno di 3 numeri:", numeri)
else:
    top3 = np.sort(numeri)[-3:] # (::1 ordina i numeri dal 
    print("I tre numeri più grandi sono:", top3)

La lista ha meno di 3 numeri: [ 5 25]


In [51]:
# esercizio 8
# Scrivere un programma che • 
# in input acquisisce una lista di numeri e un numero K 
# in output, dovrà restituire la media di tutti i numeri nella lista maggiori o uguali a K 
# se non ce ne dovesse essere nessuno, dovrà stampare a schermo un messaggio adeguato.

In [11]:
import numpy as np

lista = np.array([14, 28, 100, 46, 99, 67, 1, 9, 456, 90, 55, 43, 80, 7])
K = float(input("Inserisci a piacere un numero K: "))

filtro = lista[lista >= K]

if len(filtro) == 0:
    print("Dato il numero K scelto, nessun numero della lista è maggiore o uguale a K, per cui non è possibile calcolare la media")
else:
    media_K = filtro.mean()
    print("La media dei valori maggiori o uguali a", K, "è", media_K)


Inserisci a piacere un numero K:  9


La media dei valori maggiori o uguali a 9.0 è 90.58333333333333


In [59]:
# esercizio 9
numeri = [5, 2, 3, 4]

for n in numeri:
    print( "*" * n) 

*****
**
***
****


In [12]:
# esercizio 10
lista_cf = ["ABCDEF95G01A123B", "GHIJKL91M02A321C", "MNOPQR89S03A456D", "STUVWX95Z04A654E", "XYZABC01D05A789F", "DEFGHI95J06A987G"]

In [18]:
lista_cf_95=[]
for cf in lista_cf:
    if "95" in cf:
         lista_cf_95.append(cf)
         print(cf)

print(lista_cf_95)


ABCDEF95G01A123B
STUVWX95Z04A654E
DEFGHI95J06A987G
['ABCDEF95G01A123B', 'STUVWX95Z04A654E', 'DEFGHI95J06A987G']


In [19]:
# prendo anche nomi e cognomi
lista_cf_95=[]
for cf in lista_cf:
    if "95" in cf:
         lista_cf_95.append(cf)
         print(cf, "-", cf[:3], cf[3:6])

print(lista_cf_95)

ABCDEF95G01A123B - ABC DEF
STUVWX95Z04A654E - STU VWX
DEFGHI95J06A987G - DEF GHI
['ABCDEF95G01A123B', 'STUVWX95Z04A654E', 'DEFGHI95J06A987G']


In [1]:
# esercizio 11
studenti = [
    "Alex", 
    "Bob", 
    "Cindy", 
    "Dan", 
    "Emma", 
    "Faith",
    "Grace", 
    "Henry"
] 
corsi = [
    "Cybersecurity", 
    "Data Analyst", 
    "Backend", 
    "Frontend", 
    "Data Analyst", 
    "Backend", 
    "Frontend", 
    "Cybersecurity"
] 
edizioni = [
    1, 
    2, 
    3, 
    2, 
    2, 
    1, 
    3, 
    3
]

In [20]:
for contatore in range(len(edizioni)):
    edizione = edizioni[contatore]
    if edizione == 1:
        studente = studenti[contatore] # studenti che stanno alla prima edizione
        print(studente)

# i dati non necessari sono quelli relativi ai corsi


Alex
Faith


In [25]:
# esercizio 12
prezzi = ["100 €", "200 €", "500 €", "10 €", "50 €", "70 €"]

prezzi_aggiustati = []     # <-- la crei qui

for prezzo in prezzi:
    prezzo_adj = prezzo.replace("€", "$")
    prezzi_aggiustati.append(prezzo_adj)

print(prezzi_aggiustati)


['100 $', '200 $', '500 $', '10 $', '50 $', '70 $']


In [32]:
# esercizio 13
# vogliamo dividere gli studenti in due squadre per un campionato di Uno nel seguente modo: 
# selezioneremo i nomi in posizione pari per un squadra, e i nomi in posizione dispari per l'altra.
import numpy as np

studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry", "Isabelle", "John"]
nome = np.array(studenti)

squadra_pari = []
squadra_dispari = []

for i in range(len(nome)):
    if i % 2 == 0:
        squadra_pari.append(nome[i])
    else:
        squadra_dispari.append(nome[i])

print("Squadra pari:", squadra_pari)
print("Squadra dispari:", squadra_dispari)


Squadra pari: ['Alex', 'Cindy', 'Emma', 'Grace', 'Isabelle']
Squadra dispari: ['Bob', 'Dan', 'Faith', 'Henry', 'John']


In [33]:
# esercizio 14
# dobbiamo confrontare, stampando tutto a video, il guadagno di ogni mese con la media dei guadagni precedenti, 
# e specificare nell'output se il guadagno attuale è maggiore o minore della media dei precedenti.
guadagni = [100, 90, 70, 40, 50, 80, 90, 120, 80, 20, 50, 50]



In [35]:
for i in range(len(guadagni)):
    if i == 0:
        print(f"Mese {i+1}: guadagno = {guadagni[i]} (nessun mese precedente)")
    else:
        media_precedenti = sum(guadagni[:i]) / i
        if guadagni[i] > media_precedenti:
            confronto = "maggiore"
        elif guadagni[i] < media_precedenti:
            confronto = "minore"
        else:
            confronto = "uguale"
        print(f"Mese {i+1}: guadagno = {guadagni[i]}, media precedenti = {media_precedenti:.2f} → {confronto}")


Mese 1: guadagno = 100 (nessun mese precedente)
Mese 2: guadagno = 90, media precedenti = 100.00 → minore
Mese 3: guadagno = 70, media precedenti = 95.00 → minore
Mese 4: guadagno = 40, media precedenti = 86.67 → minore
Mese 5: guadagno = 50, media precedenti = 75.00 → minore
Mese 6: guadagno = 80, media precedenti = 70.00 → maggiore
Mese 7: guadagno = 90, media precedenti = 71.67 → maggiore
Mese 8: guadagno = 120, media precedenti = 74.29 → maggiore
Mese 9: guadagno = 80, media precedenti = 80.00 → uguale
Mese 10: guadagno = 20, media precedenti = 80.00 → minore
Mese 11: guadagno = 50, media precedenti = 74.00 → minore
Mese 12: guadagno = 50, media precedenti = 71.82 → minore
